# Generated by Django 2.1.3 on 2020-03-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebStackPage', '0002_auto_20200322_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='content',
        ),
    ]
