# Generated by Django 2.1.3 on 2020-03-22 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebStackPage', '0003_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='href_id',
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebStackPage.menu'),
        ),
    ]
