# Generated by Django 2.1.3 on 2020-03-22 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebStackPage', '0004_auto_20200322_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.DeleteModel(
            name='content',
        ),
    ]
