# Generated by Django 2.1.3 on 2020-03-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebStackPage', '0008_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='icon_img',
            field=models.TextField(default=1, verbose_name='icon'),
            preserve_default=False,
        ),
    ]
