# Generated by Django 2.1.3 on 2020-04-19 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebStackPage', '0009_content_icon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='WebStackPage.menu'),
        ),
    ]
